### ISSUE TITLE
History endpoint

### ISSUE THREAD

**Issue by vertex101** [Mxrk/tracker-poe#3]
when you try to use the history end-point you just get a message that says wrong league

**Comment by Mxrk** [comment]
Hey, thanks for reporting.  You mean something like `.../history?id=470&league=Heist`? I can't reproduce that problem, did you maybe enter a wrong league?

I also restarted the service a couple of hours ago because I added a new feature, but the "downtime" was only around 5-10 seconds... maybe that happened exactly when you tried to use that endpoint.

**Comment by vertex101** [comment]
Well I was trying to pull data from a past league but I guess that isn’t do able 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Mxrk** [comment]
Oh, you're right - that isn't possible at the moment. But I still have the old prices stored so I can add that. Will answer here when I am done, probably this weekend.

**Comment by Mxrk** [comment]
Hi, now the history endpoint also supports old leagues. I started in the last week of harvest, so that will be the oldest available data. Does it now work like expected?
